---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: freenas-api-nas
spec:
  interval: 30m
  chart:
    spec:
      chart: democratic-csi
      version: 0.10.2
      sourceRef:
        kind: HelmRepository
        name: democratic-csi
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  valuesFrom:
    - targetPath: driver.config.httpConnection.apiKey
      kind: Secret
      name: democratic-csi-freenas-api-token
      valuesKey: DEMOCRATIC_CSI_FREENAS_API_TOKEN
  values:
    csiDriver:
      name: org.democratic-csi.nfs
    driver:
      config:
        driver: freenas-api-nfs
        instance_id:
        httpConnection:
          apiVersion: 2
          host: truenas.tail419a1.ts.net
          protocol: https
          port: 443
          allowInsecure: true
        zfs:
          datasetProperties:
            "org.freenas:description": "{{ parameters.[csi.storage.k8s.io/pvc/namespace] }}/{{ parameters.[csi.storage.k8s.io/pvc/name] }}"
          datasetParentName: main/kubernetes/main/volumes
          detachedSnapshotsDatasetParentName: main/kubernetess/main/snapshots
          datasetEnableQuotas: true
          datasetEnableReservation: false
          datasetPermissionsMode: "0777"
          datasetPermissionsUser: 0
          datasetPermissionsGroup: 0
          # not supported yet
          #datasetPermissionsAcls:
          #- "-m everyone@:full_set:allow"
          #- "-m u:kube:full_set:allow"
        nfs:
          shareHost: tailscale.tail419a1.ts.net
          shareAlldirs: false
          shareAllowedHosts: []
          shareAllowedNetworks: []
          shareMaprootUser: root
          shareMaprootGroup: root
          shareMapallUser: ""
          shareMapallGroup: ""
