---
apiVersion: nfd.k8s-sigs.io/v1alpha1
kind: NodeFeatureRule
metadata:
  name: coral-tpu
spec:
  rules:
    - name:  coral-tpu-usb
      labels:
        feature.node.kubernetes.io/tpu: coral-usb
      matchAny:
        - matchFeatures:
          - feature: usb.device
            matchExpressions:
              vendor: {op: In, value: ["1a6e"]}
              device: {op: In, value: ["089a"]}
        - matchFeatures:
          - feature: usb.device
            matchExpressions:
                vendor: {op: In, value: ["18d1"]}
                device: {op: In, value: ["9302"]}
