---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/helmrepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: node-feature-discovery
  namespace: &namespace kube-system
spec:
  interval: 2h
  url: https://kubernetes-sigs.github.io/node-feature-discovery/charts
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: node-feature-discovery
  namespace: &namespace kube-system
spec:
  interval: 30m
  chart:
    spec:
      chart: node-feature-discovery
      version: 0.17.2
      sourceRef:
        kind: HelmRepository
        name: node-feature-discovery
        namespace: *namespace
  install:
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    crds: CreateReplace
    remediation:
      strategy: rollback
      retries: 3
  values:
    nodeFeatureRule.createCRD	: true

    worker:
      config:
        core:
          sources: ["pci", "system", "usb"]
      resources:
        requests:
          cpu: 1m
          memory: 64Mi
        limits:
          memory: 512Mi

    master:
      resources:
        requests:
          cpu: 1m
          memory: 128Mi
        limits:
          memory: 4Gi

    gc:
      resources:
        requests:
          cpu: 1m
          memory: 128Mi
        limits:
          memory: 1Gi

    prometheus:
      enable: true
