apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: edgetpu-device-plugin
  namespace: kube-system
  labels:
    app.kubernetes.io/name: edgetpu-device-plugin
spec:
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/name: edgetpu-device-plugin
  template:
    metadata:
      labels:
        app.kubernetes.io/name: edgetpu-device-plugin
    spec:
      priorityClassName: system-node-critical
      tolerations:
        - operator: "Exists"
          effect: "NoExecute"
        - operator: "Exists"
          effect: "NoSchedule"
      containers:
        - name: edgetpu-device-plugin
          image: ghcr.io/judahrand/edgetpu-device-plugin:latest
          command:
            - /bin/edgetpu-device-plugin
            - -v=99
          resources:
            requests:
              cpu: 50m
              memory: 10Mi
            limits:
              cpu: 50m
              memory: 20Mi
          securityContext:
            privileged: true
          volumeMounts:
            - name: devfs
              mountPath: /dev
            - name: sysfs
              mountPath: /sys
            - name: optfs
              mountPath: /opt/edgetpu
            - name: device-plugin
              mountPath: /var/lib/kubelet/device-plugins
      volumes:
        - name: devfs
          hostPath:
            path: /dev
        - name: sysfs
          hostPath:
            path: /sys
        - name: optfs
          hostPath:
            path: /opt/edgetpu
        - name: device-plugin
          hostPath:
            path: /var/lib/kubelet/device-plugins
