---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cross-seed
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: cross-seed-secret
    template:
      data:
        config.js: |
          module.exports = {
            action: "inject",
            apiKey: "{{ .cross_seed_api_key }}",
            delay: 30,
            duplicateCategories: true,
            flatLinking: false,
            includeEpisodes: true,
            includeNonVideos: true,
            includeSingleEpisodes: true,
            linkCategory: "cross-seed",
            linkDirs: ["/media/Downloads/qbittorrent/complete/cross-seed"],
            linkType: "hardlink",
            matchMode: "safe",
            outputDir: null,
            port: Number(process.env.CROSS_SEED_PORT),
            qbittorrentUrl: "http://{{ .qbittorrent_username }}:{{ .qbittorrent_password }}@qbittorrent.downloads.svc.cluster.local:8080",
            radarr: [
              "http://radarr.downloads.svc.cluster.local/?apikey={{ .radarr_api_key }}",
            ],
            skipRecheck: true,
            sonarr: [
              "http://sonarr.downloads.svc.cluster.local/?apikey={{ .sonarr_api_key }}",
            ],
            torznab: [],
            useClientTorrents: true
          };
  dataFrom:
    - extract:
        key: prowlarr
      rewrite:
        - regexp:
            source: "(.*)"
            target: "prowlarr_$1"
    - extract:
        key: radarr
      rewrite:
        - regexp:
            source: "(.*)"
            target: "radarr_$1"
    - extract:
        key: sonarr
      rewrite:
        - regexp:
            source: "(.*)"
            target: "sonarr_$1"
    - extract:
        key: cross-seed
      rewrite:
        - regexp:
            source: "(.*)"
            target: "cross_seed_$1"
    - extract:
        key: qbittorrent
      rewrite:
        - regexp:
            source: "(.*)"
            target: "qbittorrent_$1"
