---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudnative-pg
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: cloudnative-pg-secret
    template:
      engineVersion: v2
      metadata:
        labels:
          cnpg.io/reload: "true"
      data:
        POSTGRES_SUPER_USER: "{{ .POSTGRES_SUPER_USER }}"
        POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
        MINIO_USER: "{{ .MINIO_USER }}"
        MINIO_PASSWORD: "{{ .MINIO_PASSWORD }}"
  dataFrom:
    - extract:
        key: cloudnative-pg
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudnative-pg-authentik
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: cloudnative-pg-authentik-secret
    template:
      metadata:
        labels:
          cnpg.io/reload: "true"
      data:
            username: "{{ .postgres_user }}"
            password: "{{ .postgres_password }}"
  dataFrom:
    - extract:
        key: authentik
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudnative-pg-homeassistant
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: cloudnative-pg-homeassistant-secret
    template:
      metadata:
        labels:
          cnpg.io/reload: "true"
      data:
            username: "{{ .hass_postgres_user }}"
            password: "{{ .hass_postgres_password }}"
  dataFrom:
    - extract:
        key: home-assistant
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudnative-pg-kyoo
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: cloudnative-pg-kyoo-secret
    template:
      metadata:
        labels:
          cnpg.io/reload: "true"
      data:
            username: "{{ .postgres_user }}"
            password: "{{ .postgres_password }}"
  dataFrom:
    - extract:
        key: kyoo
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudnative-pg-vikunja
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: cloudnative-pg-vikunja-secret
    template:
      metadata:
        labels:
          cnpg.io/reload: "true"
      data:
            username: "{{ .postgres_user }}"
            password: "{{ .postgres_password }}"
  dataFrom:
    - extract:
        key: vikunja
