---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: judahrand-net-tls
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: judahrand-net-tls
    template:
      engineVersion: v2
      type: kubernetes.io/tls
  dataFrom:
    - extract:
        key: judahrand-net-tls
        decodingStrategy: Auto
