
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: qbtools-login
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: qbtools-login-secret
    template:
      type: Opaque
      data:
        QBITTORRENT_USER: '{{ .username }}'
        QBITTORRENT_PASS: '{{ .password }}'
  dataFrom:
    - extract:
        key: qbittorrent
