---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: frigate-config
spec:
  capacity:
    storage: 500Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOncePod
  persistentVolumeReclaimPolicy: Delete
  nfs:
    path: /mnt/main/frigate/config
    server: truenas.lan
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: frigate-media
spec:
  capacity:
    storage: 120Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOncePod
  persistentVolumeReclaimPolicy: Delete
  nfs:
    path: /mnt/main/frigate/media
    server: truenas.lan
