---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: frigate-media
spec:
  capacity:
    storage: 120Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOncePod
  persistentVolumeReclaimPolicy: Delete
  nfs:
    path: /mnt/main/frigate/media
    server: truenas.servers
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: frigate-media
spec:
  volumeName: frigate-media
  accessModes:
    - ReadWriteOncePod
  resources:
    requests:
      storage: 120Gi
