---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &appname dawarich
  namespace: &namespace selfhosted
spec:
  targetNamespace: *namespace
  commonMetadata:
    labels:
      app.kubernetes.io/name: *appname
  components:
    - ../../../../components/volsync
  interval: 1h
  timeout: 5m
  path: ./kubernetes/apps/selfhosted/dawarich/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: false
  dependsOn:
    - name: dawarich-database
      namespace: *namespace
    - name: onepassword
      namespace: external-secrets
    - name: rook-ceph-cluster
      namespace: rook-ceph
    - name: volsync
      namespace: volsync-system
  postBuild:
    substitute:
      APP: *appname
      VOLSYNC_CAPACITY: 10Gi
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app dawarich-database
  namespace: &namespace selfhosted
spec:
  targetNamespace: *namespace
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: cloudnative-pg
      namespace: cnpg-system
    - name: external-secrets
      namespace: external-secrets
  path: ./kubernetes/apps/selfhosted/dawarich/database
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: false
  interval: 1h
  retryInterval: 2m
  timeout: 5m
  postBuild:
    substitute:
      APP: *app
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app dawarich-valkey
  namespace: &namespace selfhosted
spec:
  targetNamespace: *namespace
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: external-secrets
      namespace: external-secrets
  path: ./kubernetes/apps/selfhosted/dawarich/valkey
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: false
  interval: 1h
  retryInterval: 2m
  timeout: 5m
  postBuild:
    substitute:
      APP: *app
