---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: dawarich
spec:
  targetNamespace: selfhosted
  components:
    - ../../../../components/kopiur/backup
  interval: 1h
  path: ./kubernetes/apps/selfhosted/dawarich/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: false
  dependsOn:
    - name: dawarich-database
      namespace: selfhosted
    - name: onepassword-connect
      namespace: external-secrets
    - name: rook-ceph-cluster
      namespace: rook-ceph
  postBuild:
    substitute:
      APP: dawarich
      KOPIUR_CAPACITY: 10Gi
---
yaml-language-server: $schema=https://k8s-schemas.home-operations.com/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: dawarich-database
spec:
  targetNamespace: selfhosted
  dependsOn:
    - name: cloudnative-pg
      namespace: cnpg-system
    - name: external-secrets
      namespace: external-secrets
  path: ./kubernetes/apps/selfhosted/dawarich/database
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: false
  interval: 1h
  postBuild:
    substitute:
      APP: dawarich-database
---
yaml-language-server: $schema=https://k8s-schemas.home-operations.com/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: dawarich-valkey
spec:
  targetNamespace: selfhosted
  dependsOn:
    - name: external-secrets
      namespace: external-secrets
  path: ./kubernetes/apps/selfhosted/dawarich/valkey
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: false
  interval: 1h
  postBuild:
    substitute:
      APP: dawarich-valkey
