---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app ollama
  namespace: selfhosted
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:

    controllers:
      main:
        type: deployment
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          main:
            image:
              repository: docker.io/ollama/ollama
              tag: 0.4.7-rocm
            env:
              TZ: ${TIMEZONE}
              # LIBVA_DRIVER_NAME: i965
              OLLAMA_HOST: 0.0.0.0
              OLLAMA_ORIGINS: "*"
              OLLAMA_MODELS: /models
              HSA_OVERRIDE_GFX_VERSION: "11.0.0"
            # securityContext:
            #   privileged: true
            resources:
              requests:
                cpu: 200m
                memory: 4Gi
                # gpu.intel.com/i915: "1"
              limits:
                memory: 24Gi
                # gpu.intel.com/i915: "1"

    service:
      main:
        controller: main
        ports:
          http:
            port: &port 11434

    persistence:
      models:
        storageClass: openebs-hostpath
        accessMode: ReadWriteOnce
        size: 50Gi
        advancedMounts:
          main:
            main:
              - path: /models
                subPath: models
