---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: freenas-api-iscsi
spec:
  interval: 30m
  chart:
    spec:
      chart: democratic-csi
      version: 0.14.6
      sourceRef:
        kind: HelmRepository
        name: democratic-csi
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  valuesFrom:
    - targetPath: driver.config.httpConnection.apiKey
      kind: Secret
      name: democratic-csi-freenas-api-token
      valuesKey: DEMOCRATIC_CSI_FREENAS_API_TOKEN
    - targetPath: storageClasses[0].secrets.node-stage-secret.node-db\.node\.session\.auth\.username
      kind: Secret
      name: democratic-csi-freenas-api-iscsi
      valuesKey: USER
    - targetPath: storageClasses[0].secrets.node-stage-secret.node-db\.node\.session\.auth\.password
      kind: Secret
      name: democratic-csi-freenas-api-iscsi
      valuesKey: SECRET
    - targetPath: storageClasses[0].secrets.node-stage-secret.node-db\.node\.session\.auth\.username_in
      kind: Secret
      name: democratic-csi-freenas-api-iscsi
      valuesKey: USER
    - targetPath: storageClasses[0].secrets.node-stage-secret.node-db\.node\.session\.auth\.password_in
      kind: Secret
      name: democratic-csi-freenas-api-iscsi
      valuesKey: PEER_SECRET
  values:
    csiDriver:
      name: org.democratic-csi.iscsi

    driver:
      config:
        driver: freenas-api-iscsi
        instance_id:
        httpConnection:
          apiVersion: 2
          host: truenas.lan
          protocol: http
          port: 80
          allowInsecure: true
        zfs:
          datasetProperties:
            "org.truenas:description": "{{ parameters.[csi.storage.k8s.io/pvc/namespace] }}/{{ parameters.[csi.storage.k8s.io/pvc/name] }}"
          datasetParentName: main/kubernetes/main/iscsi/volumes
          detachedSnapshotsDatasetParentName: main/kubernetess/main/iscsi/snapshots
          datasetEnableQuotas: true
          datasetEnableReservation: false
          datasetPermissionsMode: "0750"
          datasetPermissionsUser: 3004  # democratic-csi
          datasetPermissionsGroup: 3004  # democratic-csi

          zvolCompression: "off"
          zvolBlocksize: 4k
        iscsi:
          targetPortal: truenas.lan:3260
          nameTemplate: "{{ parameters.[csi.storage.k8s.io/pvc/namespace] }}-{{ parameters.[csi.storage.k8s.io/pvc/name] }}"

          targetGroups:
            # get the correct ID from the "portal" section in the UI
            # https://github.com/democratic-csi/democratic-csi/issues/302
            # NOTE: the ID in the UI does NOT always match the ID in the DB, you must use the DB value
            - targetGroupPortalGroup: 2
              # get the correct ID from the "initiators" section in the UI
              targetGroupInitiatorGroup: 2
              # None, CHAP, or CHAP Mutual
              targetGroupAuthType: CHAP Mutual
              # get the correct ID from the "Authorized Access" section of the UI
              # only required if using Chap
              targetGroupAuthGroup: 3004

          extentRpm: "7200"

    node:
      hostPID: true
      driver:
        extraEnv:
          - name: ISCSIADM_HOST_STRATEGY
            value: nsenter
          - name: ISCSIADM_HOST_PATH
            value: /usr/local/sbin/iscsiadm
        iscsiDirHostPath: /usr/local/etc/iscsi
        iscsiDirHostPathType: ""

    storageClasses:
      - name: freenas-api-iscsi
        defaultClass: false
        reclaimPolicy: Delete
        volumeBindingMode: Immediate
        allowVolumeExpansion: true
        parameters:
          fsType: ext4
        mountOptions: []
        secrets:
          provisioner-secret:
          controller-publish-secret:
          node-stage-secret:
            node-db.node.session.auth.authmethod: CHAP
          node-publish-secret:
        controller-expand-secret:
