---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: openwrt-backup
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: openwrt-backup-secret
    template:
      engineVersion: v2
      data:
        OPENWRT_HOSTS: "{{ .hosts }}"
        SSH_KEY: "{{ .ssh_key | b64dec }}"
        KNOWN_HOSTS: "{{ .known_hosts }}"
        RUSTIC_PASSWORD: "{{ .restic_password }}"
        OPENDAL_ACCESS_KEY_ID: "{{ .aws_access_key_id }}"
        OPENDAL_SECRET_ACCESS_KEY: "{{ .aws_secret_access_key }}"
        OPENDAL_ENDPOINT: "{{ .s3_endpoint }}"
        OPENDAL_BUCKET: "{{ .s3_bucket }}"
        OPENDAL_REGION: "{{ .s3_region }}"
  dataFrom:
    - extract:
        key: openwrt
