---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: operator
spec:
  interval: 30m
  chart:
    spec:
      chart: tailscale-operator
      version: 1.76.1
      sourceRef:
        kind: HelmRepository
        name: tailscale
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    apiServerProxyConfig:
      mode: "true"
