---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: minio
spec:
  interval: 30m
  chart:
    spec:
      chart: minio
      version: 5.2.0
      sourceRef:
        kind: HelmRepository
        name: minio
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    image:
      repository: quay.io/minio/minio
      tag: RELEASE.2024-09-13T20-26-02Z

    mcImage:
      repository: quay.io/minio/mc
      tag: RELEASE.2024-09-13T20-26-02Z

    mode: standalone
    existingSecret: minio-secret

    # Number of drives attached to a node
    drivesPerNode: 1
    # Number of MinIO containers running
    replicas: 1
    # Number of expanded MinIO clusters
    pools: 1

    tenant:
      name: minio
      pools:
        - name: pool-0
          servers: 1
          volumesPerServer: 1
          size: 500Gi
          storageClassName: minio
      features:
        bucketDNS: true

