apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: minio
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
provisioner: nfs.csi.k8s.io
reclaimPolicy: Retain
allowVolumeExpansion: true
volumeBindingMode: Immediate
mountOptions:
  - noatime
  - nfsvers=4.2
  - nolock
parameters:
  server: truenas.tail419a1.ts.net
  share: /mnt/main/minio
  onDelete: retain
