---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: home-assistant
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: home-assistant-secret
    template:
      engineVersion: v2
      data:
        # Deploy key
        GH_DEPLOY_KEY: "{{ .hass_github_deploy_key }}"
        GH_KNOWN_HOSTS: "{{ .hass_github_known_hosts }}"

        # Home-Assistant
        SECRET_INTERNAL_URL: http://${MULTUS_HOME_ASSISTANT}:8123
        SECRET_INTERNAL_URL_DIRECT: http://${MULTUS_HOME_ASSISTANT}:8123
        SECRET_EXTERNAL_URL: https://homeassistant.judahrand.net
        SECRET_TRUSTED_PROXIES_1: 10.244.0.0/16

        # Home-Assistant Zones
        SECRET_ZONE_HOME_HOUSE_NUMBER: "{{ .hass_zone_home_house_number }}"
        SECRET_ZONE_HOME_POSTAL_CODE: "{{ .hass_zone_home_postal_code }}"
        SECRET_ZONE_HOME_ELEVATION: "{{ .hass_zone_home_elevation }}"
        SECRET_ZONE_HOME_LATITUDE: "{{ .hass_zone_home_latitude }}"
        SECRET_ZONE_HOME_LONGITUDE: "{{ .hass_zone_home_longitude }}"

        # Home-Assistant Postgres
        POSTGRES_URL: >-
          postgresql://{{ .hass_postgres_user }}:{{ .hass_postgres_password }}@postgres16-rw.database.svc.cluster.local/homeassistant
        INIT_POSTGRES_DBNAME: homeassistant
        INIT_POSTGRES_HOST: postgres16-rw.database.svc.cluster.local
        INIT_POSTGRES_USER: "{{ .hass_postgres_user }}"
        INIT_POSTGRES_PASS: "{{ .hass_postgres_password }}"
        INIT_POSTGRES_SUPER_USER: postgres
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"

  dataFrom:
    - extract:
        key: home-assistant
        decodingStrategy: Auto
    - extract:
        key: cloudnative-pg
