---
image:
  repository: ghcr.io/spegel-org/spegel
  tag: v0.0.30
spegel:
  appendMirrors: true
  containerdSock: /run/containerd/containerd.sock
  containerdRegistryConfigPath: /etc/cri/conf.d/hosts
service:
  registry:
    hostPort: 29999