---
yaml-language-server: $schema=https://k8s-schemas.home-operations.com/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: dispatcharr
spec:
  targetNamespace: downloads
  dependsOn:
    - name: intel-gpu-resource-driver
      namespace: kube-system
  components:
    - ../../../../components/kopiur/backup
  path: ./kubernetes/apps/downloads/dispatcharr/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: false
  interval: 1h
  postBuild:
    substitute:
      APP: dispatcharr
      KOPIUR_CAPACITY: 10Gi
