---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: immich-redis
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      immich-redis:
        containers:
          app:
            image:
              repository: public.ecr.aws/docker/library/redis
              tag: 7.4.3
            env:
              REDIS_REPLICATION_MODE: master
            command: ["redis-server"]
            resources:
              requests:
                cpu: 100m
                memory: 256Mi
              limits:
                memory: 4096Mi
    service:
      app:
        controller: immich-redis
        ports:
          http:
            port: 6379
