---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: minio-tenant
spec:
  interval: 30m
  chart:
    spec:
      chart: tenant
      version: 6.0.3
      sourceRef:
        kind: HelmRepository
        name: minio
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  valuesFrom:
    - targetPath: tenant.configSecret.accessKey
      kind: Secret
      name: minio-secret
      valuesKey: MINIO_ROOT_USER
    - targetPath: tenant.configSecret.secretKey
      kind: Secret
      name: minio-secret
      valuesKey: MINIO_ROOT_PASSWORD
  values:
    tenant:
      name: minio
      pools:
        - name: pool-0
          servers: 1
          volumesPerServer: 1
          size: 500Gi
          storageClassName: minio
      features:
        bucketDNS: true

