---
apiVersion: v1
kind: ConfigMap
metadata:
  name: zigbee2mqtt-config
data:
  TZ: Europe/London
  ZIGBEE2MQTT_DATA: /data
  ZIGBEE2MQTT_CONFIG_ADVANCED_HOMEASSISTANT_DISCOVERY_TOPIC: homeassistant
  ZIGBEE2MQTT_CONFIG_ADVANCED_HOMEASSISTANT_LEGACY_ENTITY_ATTRIBUTES: "false"
  ZIGBEE2MQTT_CONFIG_ADVANCED_HOMEASSISTANT_LEGACY_TRIGGERS: "false"
  ZIGBEE2MQTT_CONFIG_ADVANCED_HOMEASSISTANT_STATUS_TOPIC: homeassistant/status
  ZIGBEE2MQTT_CONFIG_ADVANCED_CHANNEL: "20"
  ZIGBEE2MQTT_CONFIG_ADVANCED_LAST_SEEN: ISO_8601
  ZIGBEE2MQTT_CONFIG_ADVANCED_LEGACY_API: "false"
  ZIGBEE2MQTT_CONFIG_ADVANCED_LEGACY_AVAILABILITY_PAYLOAD: "false"
  ZIGBEE2MQTT_CONFIG_ADVANCED_LOG_LEVEL: info # debug
  ZIGBEE2MQTT_CONFIG_ADVANCED_LOG_OUTPUT: '["console"]'
  ZIGBEE2MQTT_CONFIG_AVAILABILITY_ACTIVE_TIMEOUT: "60"
  ZIGBEE2MQTT_CONFIG_AVAILABILITY_PASSIVE_TIMEOUT: "2000"
  ZIGBEE2MQTT_CONFIG_DEVICE_OPTIONS_LEGACY: "false"
  ZIGBEE2MQTT_CONFIG_DEVICE_OPTIONS_RETAIN: "true"
  ZIGBEE2MQTT_CONFIG_EXPERIMENTAL_NEW_API: "true"
  ZIGBEE2MQTT_CONFIG_HOMEASSISTANT: "true"
  ZIGBEE2MQTT_CONFIG_MQTT_INCLUDE_DEVICE_INFORMATION: "true"
  ZIGBEE2MQTT_CONFIG_MQTT_KEEPALIVE: "60"
  ZIGBEE2MQTT_CONFIG_MQTT_REJECT_UNAUTHORIZED: "true"
  ZIGBEE2MQTT_CONFIG_MQTT_SERVER: mqtt://emqx-listeners.database.svc.cluster.local:1883
  ZIGBEE2MQTT_CONFIG_MQTT_VERSION: "5"
  ZIGBEE2MQTT_CONFIG_PERMIT_JOIN: "false"
  ZIGBEE2MQTT_CONFIG_SERIAL_BAUDRATE: "115200"
  ZIGBEE2MQTT_CONFIG_SERIAL_DISABLE_LED: "false"
  ZIGBEE2MQTT_CONFIG_SERIAL_ADAPTER: ember
  ZIGBEE2MQTT_CONFIG_SERIAL_PORT: tcp://10.0.60.245:6638
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: zigbee2mqtt-healthcheck
data:
  healthcheck.sh: |
    #! /bin/sh
    set -e

    status=$(
        echo '{"topic": "zigbee2mqtt/bridge/request/health_check", "payload": {}}' \
        | websocat -1 wss://zigbee2mqtt.judahrand.net/api \
        | jq --raw-output '.payload.state'
    )

    if [ "$status" = "online" ]; then
        echo "online"
        exit 0
    else
        echo "offline"
        exit 1
    fi;
