---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app sabnzbd
  namespace: flux-system
spec:
  targetNamespace: downloads
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  components:
    - ../../../../components/gatus/guarded
    - ../../../../components/volsync
  interval: 30m
  timeout: 5m
  path: ./kubernetes/apps/downloads/sabnzbd/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: false
  dependsOn:
    - name: openebs
      namespace: openebs-system
    - name: external-secrets
  postBuild:
    substitute:
      APP: *app
      GATUS_SUBDOMAIN: sab
      VOLSYNC_CAPACITY: 1Gi
