---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: goldilocks
spec:
  interval: 30m
  chart:
    spec:
      chart: goldilocks
      version: 9.0.1
      sourceRef:
        kind: HelmRepository
        name: fairwinds
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    dashboard:
      ingress:
        enabled: true
        ingressClassName: internal
        annotations:
          external-dns.alpha.kubernetes.io/target: internal.judahrand.net
        hosts:
          - host: goldilocks.judahrand.net
            paths:
              - path: /
                type: ImplementationSpecific
