---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app nut-exporter
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    fullnameOverride: *app
    controllers:
      nut-exporter:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/druggeri/nut_exporter
              tag: 3.2.0
            env:
              TZ: Europe/London
            args:
              # the first time I set this, the first and last entries were ignored, so I have doubled them.
              - --nut.vars_enable="battery.charge,battery.charge,battery.runtime,battery.voltage,battery.voltage.nominal,input.voltage,input.voltage.nominal,output.voltage,output.voltage.nominal,ups.realpower,ups.load,ups.status,ups.status"
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
              startup:
                enabled: true
            resources:
              limits:
                cpu: 100m
                memory: 200Mi
    service:
      app:
        controller: *app
        ports:
          metrics:
            enabled: true
            protocol: TCP
            port: 9199
    serviceMonitor:
      app:
        enabled: true
        serviceName: *app
        endpoints:
          - interval: 30s
            path: /ups_metrics
            port: metrics
            scheme: http
            scrapeTimeout: 30s
            metricRelabelings:
              - action: replace
                replacement: server
                sourceLabels:
                  - instance
                targetLabel: instance
              - action: replace
                replacement: server
                sourceLabels:
                  - server
                targetLabel: server
              - action: labeldrop
                regex: (pod)
            params:
              server: [http://apc227469.lan/]
            selector:
              matchLabels:
                app.kubernetes.io/instance: nut-exporter
                app.kubernetes.io/name: nut-exporter
