---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./helmrelease.yaml
  - ./prometheusrule.yaml
configMapGenerator:
  - name: nut-exporter-dashboard
    files:
      - ./resources/nut-exporter.json
  - name: ups-aggregate-dashboard
    files:
      - ./resources/ups-aggregate.json
generatorOptions:
  disableNameSuffixHash: true
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled
    grafana_folder: "System"
  labels:
    grafana_dashboard: "true"
