
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: home-assistant
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.6.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      home-assistant:
        annotations:
          reloader.stakater.com/auto: "true"

        pod:
          annotations:
              k8s.v1.cni.cncf.io/networks: |
                [{
                  "name":"iot-vlan",
                  "namespace": "network",
                  "ips": ["${MULTUS_HOME_ASSISTANT}/24"],
                  "mac": "a0:41:a7:f2:2e:fe"
                }]

        initContainers:
          init-db:
            image:
              repository: ghcr.io/onedr0p/postgres-init
              tag: 16
            envFrom: &envFrom
              - secretRef:
                  name: home-assistant-secret

        containers:
          app:
            image:
              repository: ghcr.io/onedr0p/home-assistant
              tag: 2025.1.4
            env:
              TIMEZONE: "${TIMEZONE}"
              UV_NO_CACHE: "true"
            envFrom: *envFrom
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop: ["ALL"]
              sysctls:
                - name: net.ipv6.conf.net1.forwarding
                  value: "0"
                - name: net.ipv6.conf.net1.accept_ra
                  value: "1"
                - name: net.ipv6.conf.net1.accept_ra_rt_info_max_plen
                  value: "64"
            resources:
              requests:
                cpu: 50m
                memory: 1Gi
              limits:
                memory: 4Gi

          code-server:
            image:
              repository: ghcr.io/coder/code-server
              tag: 4.96.4@sha256:f93810f7f6636b3af3b1a750faf612349cddb89fbb6d28d69123a214fc75ee9e
            args: [
              "--auth", "none",
              "--user-data-dir", "/config/.vscode",
              "--extensions-dir", "/config/.vscode",
              "--port", "12321",
              "/config"
            ]
            resources:
              requests:
                cpu: 10m
                memory: 256M
              limits:
                memory: 512M

    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 568
        runAsGroup: 568
        fsGroup: 568
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile: { type: RuntimeDefault }

    service:
      app:
        controller: home-assistant
        ports:
          http:
            port: 8123
          code-server:
            port: 12321

    ingress:
      app:
        annotations:
          external-dns.alpha.kubernetes.io/target: external.judahrand.net
        className: external
        hosts:
          - host: homeassistant.judahrand.net
            paths:
              - path: /
                service:
                  identifier: app
                  port: http

      code-server:
        annotations:
          external-dns.alpha.kubernetes.io/target: internal.judahrand.net
        className: internal
        hosts:
          - host: hass-code.judahrand.net
            paths:
              - path: /
                service:
                  identifier: app
                  port: code-server

    persistence:
      config:
        existingClaim: home-assistant
        globalMounts:
          - path: /config

      tmp:
        type: emptyDir
        globalMounts:
          - path: /tmp

      deploy-key:
        type: secret
        name: home-assistant-secret
        defaultMode: 256
        globalMounts:
          - path: /root/.ssh/id_ed25519
            subPath: GH_DEPLOY_KEY
          - path: /root/.ssh/known_hosts
            subPath: GH_KNOWN_HOSTS
