---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: democratic-csi-freenas-api-token
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: democratic-csi-freenas-api-token
    template:
      engineVersion: v2
      data:
        DEMOCRATIC_CSI_FREENAS_API_TOKEN: |-
          {{ .credential }}
  dataFrom:
    - extract:
        key: democratic-csi-freenas-api-token
