---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: frigate-config
spec:
  volumeName: frigate-config
  accessModes:
    - ReadWriteOncePod
  resources:
    requests:
      storage: 500Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: frigate-media
spec:
  volumeName: frigate-media
  accessModes:
    - ReadWriteOncePod
  resources:
    requests:
      storage: 120Gi
