---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: vikunja
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: vikunja-secret
    template:
      type: Opaque
      data:
        VIKUNJA_DATABASE_TYPE: postgres
        VIKUNJA_DATABASE_HOST: &dbHost postgres16-rw.cnpg-system.svc.cluster.local
        VIKUNJA_DATABASE_DATABASE: &dbName vikunja
        VIKUNJA_DATABASE_USER: &dbUser "{{ .postgres_user }}"
        VIKUNJA_DATABASE_PASSWORD: &dbPass "{{ .postgres_password }}"
        INIT_POSTGRES_DBNAME: *dbName
        INIT_POSTGRES_HOST: *dbHost
        INIT_POSTGRES_USER: *dbUser
        INIT_POSTGRES_PASS: *dbPass
        INIT_POSTGRES_SUPER_USER: "{{ .POSTGRES_SUPER_USER }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
    - extract:
        key: vikunja
    - extract:
        key: cloudnative-pg
