---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: dawarich
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: dawarich-secret
    template:
      data:
        # App
        SECRET_KEY_BASE: "{{ .secret_key_base }}"
        REDIS_URL: |-
          redis://:{{ .valkey_password }}@dawarich-valkey:6379
        # Database
        DATABASE_HOST: dawarich-database-rw
        DATABASE_PORT: "5432"
        DATABASE_USERNAME: "{{ .postgres_user }}"
        DATABASE_PASSWORD: "{{ .postgres_password }}"
        DATABASE_NAME: "dawarich"
  dataFrom:
    - extract:
        key: dawarich
