---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app open-webui
  namespace: default
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      open-webui:
        replicas: 1
        containers:
          app:
            image:
              repository: ghcr.io/open-webui/open-webui
              tag: main
            env:
              OLLAMA_BASE_URL: http://ollama.selfhosted.svc.cluster.local:11434
              DATA_DIR: /data

    service:
      app:
        controller: open-webui
        ports:
          http:
            port: &port 8080

    route:
      app:
        hostnames:
          - "{{ .Release.Name }}.judahrand.net"
        parentRefs:
          - name: internal
            namespace: kube-system
            sectionName: https
        rules:
          - backendRefs:
              - name: app
                port: *port

    persistence:
     config:
       existingClaim: open-webui
       globalMounts:
         - path: /data
