---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app open-webui
  namespace: default
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      open-webui:
        replicas: 1
        containers:
          app:
            image:
              repository: ghcr.io/open-webui/open-webui
              tag: main
            env:
              OLLAMA_BASE_URL: http://ollama:11434
              DATA_DIR: /data

    service:
      app:
        controller: open-webui
        ports:
          http:
            port: 8080

    ingress:
      app:
        className: internal
        annotations:
          external-dns.alpha.kubernetes.io/target: internal.judahrand.net
        hosts:
          - host: open-webui.judahrand.net
            paths:
              - path: /
                service:
                  identifier: app
                  port: http

    persistence:
     config:
       existingClaim: open-webui
       globalMounts:
         - path: /data
