---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: "${APP}-volsync"
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: "${APP}-volsync-secret"
    template:
      data:
        RESTIC_REPOSITORY: "rest:http://truenas.servers:8000/{{ .restic_rest_username }}/${APP}"
        RESTIC_PASSWORD: "{{ .restic_password }}"
        RESTIC_REST_USERNAME: "{{ .restic_rest_username }}"
        RESTIC_REST_PASSWORD: "{{ .restic_rest_password }}"
  dataFrom:
    - extract:
        key: volsync-template
