---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: metrics-server
spec:
  interval: 30m
  chart:
    spec:
      chart: metrics-server
      version: 3.12.1
      sourceRef:
        kind: HelmRepository
        name: metrics-server
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    args:
      # TODO: Work out how to securely deploy the `mertics-server`
      - --kubelet-insecure-tls
    metrics:
      enabled: true
    serviceMonitor:
      enabled: true
