---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: emqx-system
components:
  - ../../components/common
resources:
  - ./cluster/ks.yaml
  - ./emqx-operator/ks.yaml
