---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: dawarich-valkey
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: dawarich-valkey-secret
    template:
      metadata:
        labels:
          cnpg.io/reload: "true"
      data:
        password: "{{ .valkey_password }}"
  dataFrom:
    - extract:
        key: dawarich
