---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: dawarich-valkey
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: dawarich-valkey
  values:
    image:
      registry: ghcr.io
      repository: valkey-io/valkey
      tag: 9.1.1
    dataStorage:
      enabled: false
    auth:
      enabled: true
      usersExistingSecret: dawarich-valkey-secret
      aclUsers:
        default:
          permissions: "~* &* +@all"
          passwordKey: "password"
    resources:
      requests:
        cpu: 50m
        memory: 128Mi
      limits:
        memory: 512Mi
