---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jellyfin
spec:
  interval: 1h
  chart:
    spec:
      chart: app-template
      version: 3.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 1h
  maxHistory: 3
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      main:
        replicas: 1

        containers:
          main:
            image:
              repository: jellyfin/jellyfin
              tag: 10.10.0

            resources:
              requests:
                cpu: 100m
                gpu.intel.com/i915: 1
                memory: 512Mi
              limits:
                gpu.intel.com/i915: 1
                memory: 8000Mi

    service:
      main:
        type: LoadBalancer
        annotations:
          lbipam.cilium.io/ips: "${LOAD_BALANCER_JELLYFIN}"
        controller: main
        ports:
          http:
            port: 8096
          discovery:
            port: 7359
            protocol: UDP

    ingress:
      main:
        enabled: true
        className: external
        annotations:
          external-dns.alpha.kubernetes.io/target: external.judahrand.net
        hosts:
          - host: &host jellyfin.judahrand.net
            paths:
              - path: /
                service:
                  identifier: main
                  port: http
        tls:
          - hosts:
              - *host

    persistence:
      tmpfs:
        type: emptyDir
        globalMounts:
          - path: /cache

      media:
        type: nfs
        server: truenas.lan
        path: /mnt/main/media
        globalMounts:
          - path: /media

      config:
        type: nfs
        server: truenas.lan
        path: /mnt/main/jellyfin
        globalMounts:
          - path: /config
