---
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: multus-servers
spec:
  config: |-
    {
      "cniVersion": "0.3.1",
      "name": "multus-servers",
      "plugins": [
        {
          "type": "macvlan",
          "mode": "bridge",
          "capabilities": {
            "ips": true
          },
          "ipam": {
            "type": "static",
            "routes": [
              { "dst": "10.0.42.0/24", "gw": "10.0.42.1" }
            ]
          }
        }
      ]
    }

# "routes": [
#   { "dst": "10.0.42.0/24", "gw": "10.0.42.1" }
# ]
# "addresses": [
#   {
#     "address": "10.0.42.85/24",
#     "gateway": "10.0.42.1"
#   }
# ]