---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: iot-vlan
spec:
  config: |-
    {
      "cniVersion": "0.3.1",
      "name": "iot-vlan",
      "plugins": [
        {
          "type": "macvlan",
          "master": "br0",
          "mode": "bridge",
          "vlan": 60,
          "capabilities": {
            "ips": true
          },
          "ipam": {
            "type": "static",
            "routes": [
              { "dst": "10.0.60.0/24", "gw": "10.0.60.1" }
            ]
          }
        },
        {
          "capabilities": { "mac": true },
          "type": "tuning"
        }
      ]
    }