---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./esphome/ks.yaml
  - ./frigate/ks.yaml
  - ./home-assistant/ks.yaml
  - ./home-assistant-matter-hub/ks.yaml
  - ./matter-server/ks.yaml
  - ./otbr/ks.yaml
  - ./zigbee2mqtt/ks.yaml
