---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: home
components:
  - ../../components/common
resources:
  - ./esphome/ks.yaml
  - ./frigate/ks.yaml
  - ./home-assistant/ks.yaml
  - ./home-assistant-matter-hub/ks.yaml
  - ./matter-server/ks.yaml
  - ./zigbee2mqtt/ks.yaml
patches:
  - patch: |-
      apiVersion: v1
      kind: Namespace
      metadata:
        name: not-used
        labels:
          pod-security.kubernetes.io/enforce: privileged
