---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./esphome/ks.yaml
  - ./frigate/ks.yaml
  - ./multus-networks/ks.yaml
  - ./zigbee2mqtt/ks.yaml
