---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cilium
spec:
  interval: 30m
  chart:
    spec:
      chart: cilium
      version: 1.16.5
      sourceRef:
        kind: HelmRepository
        name: cilium
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  valuesFrom:
    - kind: ConfigMap
      name: cilium-helm-values
  values:
    hubble:
      enabled: true
      metrics:
        enabled:
          - dns:query
          - drop
          - tcp
          - flow
          - port-distribution
          - icmp
          - http
        serviceMonitor:
          enabled: true
        dashboards:
          enabled: true
      relay:
        enabled: true
        rollOutPods: true
        prometheus:
          serviceMonitor:
            enabled: true
        resources:
          requests:
            cpu: 5m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
      ui:
        enabled: true
        rollOutPods: true
        ingress:
          enabled: true
          annotations:
            external-dns.alpha.kubernetes.io/target: internal.judahrand.net
          className: internal
          hosts: ["hubble.judahrand.net"]
        backend:
          resources:
            requests:
              cpu: 1m
              memory: 32Mi
            limits:
              cpu: 100m
              memory: 64Mi
        frontend:
          resources:
            requests:
              cpu: 1m
              memory: 16Mi
            limits:
              cpu: 100m
              memory: 32Mi
    operator:
      prometheus:
        enabled: true
        serviceMonitor:
          enabled: true
      dashboards:
        enabled: true
      resources:
        requests:
          cpu: 10m
          memory: 256Mi
        limits:
          cpu: 1000m
          memory: 4Gi
    prometheus:
      enabled: true
      serviceMonitor:
        enabled: true
        trustCRDsExist: true
    dashboards:
      enabled: true
    resources:
      requests:
        cpu: 100m
        memory: 512Mi
      limits:
        cpu: 1000m
        memory: 4Gi
