---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: immich-tools
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3

  values:
    controllers:
      immich-stack:
        forceRename: immich-stack
        type: cronjob

        annotations:
          reloader.stakater.com/auto: "true"

        cronjob:
          schedule: "@hourly"
          timeZone: "Europe/London"
          concurrencyPolicy: Forbid
          successfulJobsHistory: 1
          failedJobsHistory: 1

        containers:
          main:
            image:
              repository: ghcr.io/judahrand/immich-stack
              tag: 0.1.19@sha256:2722b4d5e38f558e205c1fd903a2b717add1153cab8a73afc07049676c97cd6c
            env:
              TZ: Europe/London
              WITH_ARCHIVED: true
              WITH_DELETED: true
              RUN_MODE: once
              CRITERIA: >-
                [{"key":"originalFileName","split":{"delimiters":["~","."],"index":0}},{"key":"localDateTime","delta":{"milliseconds":1000}}]
            envFrom:
              - secretRef:
                  name: immich-stack-secret
            securityContext:
              runAsNonRoot: true
              runAsUser: 568
              runAsGroup: 568
              fsGroup: 568
              fsGroupChangePolicy: OnRootMismatch
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              seccompProfile: { type: RuntimeDefault }
              capabilities: { drop: ["ALL"] }
