---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: immich-tools
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3

  values:
    controllers:
      immich-stack:
        type: cronjob

        annotations:
          reloader.stakater.com/auto: "true"

        cronjob:
          schedule: "@hourly"
          timeZone: "Europe/London"
          concurrencyPolicy: Forbid
          successfulJobsHistory: 1
          failedJobsHistory: 1

        containers:
          main:
            image:
              repository: ghcr.io/judahrand/containers/immich-stack
              tag: 0.1.19@sha256:edc5a356c78900427895b97b7859d814800f46da8c481efeb2442dc42a57c634
            args:
              - backup
              - --init
              - /backup
            env:
              TZ: Europe/London
              RUN_MODE: once
              DRY_RUN: true

            envFrom:
              - secretRef:
                  name: immich-stack-secret
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
