---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app freenas-api-iscsi
  namespace: flux-system
spec:
  targetNamespace: democratic-csi
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: democratic-csi-common
  path: ./kubernetes/apps/democratic-csi/freenas-api-iscsi/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
