---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: bazarr
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: bazarr-secret
    creationPolicy: Owner
  data:
    - secretKey: api_key
      remoteRef:
        key: bazarr
        property: api_key
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: bazarr-db
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: bazarr-db-secret
    template:
      type: Opaque
      data:
        POSTGRES_ENABLED: "true"
        POSTGRES_HOST: &dbHost postgres16-rw.database.svc.cluster.local
        POSTGRES_PORT: "5432"
        POSTGRES_DATABASE: &dbName bazarr
        POSTGRES_USERNAME: &dbUser "{{ .username }}"
        POSTGRES_PASSWORD: &dbPass "{{ .password }}"
        INIT_POSTGRES_DBNAME: *dbName
        INIT_POSTGRES_HOST: *dbHost
        INIT_POSTGRES_USER: *dbUser
        INIT_POSTGRES_PASS: *dbPass
        INIT_POSTGRES_SUPER_USER: "{{ .POSTGRES_SUPER_USER }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
    - extract:
        key: postgres-pguser-bazarr
    - extract:
        key: cloudnative-pg
