---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: immich
spec:
  targetNamespace: media
  components:
  path: ./kubernetes/apps/media/immich/app
  dependsOn:
    - name: immich-database
      namespace: media
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: false
  interval: 30m
  postBuild:
    substitute:
      APP: immich
      GATUS_SUBDOMAIN: immich
---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: immich-database
spec:
  targetNamespace: media
  path: ./kubernetes/apps/media/immich/database
  dependsOn:
    - name: cloudnative-pg
      namespace: cnpg-system
    - name: external-secrets
      namespace: external-secrets
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: false
  interval: 30m
  postBuild:
    substitute:
      APP: immich-database
---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: immich-tools
spec:
  targetNamespace: media
  path: ./kubernetes/apps/media/immich/tools
  dependsOn:
    - name: immich
      namespace: media
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: false
  interval: 30m
  postBuild:
    substitute:
      APP: immich-tools
