---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gatus
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: gatus-secret
    template:
      engineVersion: v2
      data:
        PUSHOVER_TOKEN: "{{ .gatus_pushover_token }}"
        PUSHOVER_USER_KEY: "{{ .pushover_user_key }}"
        INIT_POSTGRES_DBNAME: gatus
        INIT_POSTGRES_HOST: postgres16-rw.database.svc.cluster.local
        INIT_POSTGRES_USER: "{{ .gatus_postgres_user }}"
        INIT_POSTGRES_PASS: "{{ .gatus_postgres_password }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
    - extract:
        key: cloudnative-pg
    - extract:
        key: gatus
    - extract:
        key: pushover
