---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: prowlarr
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: prowlarr-secret
    creationPolicy: Owner
  data:
    - secretKey: api_key
      remoteRef:
        key: prowlarr
        property: api_key
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: prowlarr-db
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: prowlarr-db-secret
    template:
      type: Opaque
      data:
        PROWLARR__POSTGRES__HOST: &dbHost postgres16-rw.database.svc.cluster.local
        PROWLARR__POSTGRES__PORT: "5432"
        PROWLARR__POSTGRES__MAINDB: prowlarr-main
        PROWLARR__POSTGRES__LOGDB: prowlarr-log
        PROWLARR__POSTGRES__USER: &dbUser "{{ .username }}"
        PROWLARR__POSTGRES__PASSWORD: &dbPass "{{ .password }}"
        INIT_POSTGRES_DBNAME: prowlarr-main prowlarr-log
        INIT_POSTGRES_HOST: *dbHost
        INIT_POSTGRES_USER: *dbUser
        INIT_POSTGRES_PASS: *dbPass
        INIT_POSTGRES_SUPER_USER: "{{ .POSTGRES_SUPER_USER }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
    - extract:
        key: postgres-pguser-prowlarr
    - extract:
        key: cloudnative-pg
