---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/cert-manager.io/certificate_v1.json
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: judahrand-net
spec:
  secretName: judahrand-net-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: judahrand.net
  dnsNames:
    - judahrand.net
    - "*.judahrand.net"
