---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: "Europe/London"

  # Load balancer IPs
  LOAD_BALANCER_INTERNAL_NGINX: 10.0.42.121
  LOAD_BALANCER_EXTERNAL_NGINX: 10.0.42.122
  LOAD_BALANCER_POSTGRES: 10.0.42.125
  LOAD_BALANCER_EMQX: 10.0.42.126
  LOAD_BALANCER_FRIGATE: 10.0.42.127
  LOAD_BALANCER_MATTER_SERVER: 10.0.42.128
  LOAD_BALANCER_JELLYFIN: 10.0.42.129
  LOAD_BALANCER_GRAPHITE_EXPORTER: 10.0.42.130

  # Multus IPs
  MULTUS_ESPHOME: 10.0.60.85
  MULTUS_MATTER_SERVER: 10.0.60.86
  MULTUS_HOME_ASSISTANT: 10.0.60.87
  MULTUS_HOME_ASSISTANT_MATTER_HUB: 10.0.60.88

  # Cloudflare
  CLUSTER_CLOUDFLARE_TUNNEL_ID: 32a8656e-42a1-453b-91d2-6689236bef7f

  # Users & Groups
  APP_UID: "568"
  APP_GID: "100"