---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &name kyoo
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: kyoo-secret
    template:
      type: Opaque
      data:
        # App
        KYOO_API_KEY: '{{ .KYOO_API_KEY }}'
        TMDB_API_KEY: '{{ .TMDB_API_KEY }}'
        TVDB_APIKEY: ""
        TVDB_PIN: ""
        #Meili
        MEILI_MASTER_KEY: '{{ .MEILI_MASTER_KEY }}'
        #RabbitMQ
        RABBITMQ_USER: kyoo
        RABBITMQ_ERLANG_COOKIE: '{{ .RABBITMQ_ERLANG_COOKIE}}'
        RABBITMQ_PASS: '{{ .RABBITMQ_PASS }}'
        # Postgres
        POSTGRES_DB: &dbName kyoo
        POSTGRES_SERVER: &dbHost postgres16-rw.database.svc.cluster.local
        POSTGRES_PORT: "5432"
        POSTGRES_USER: &dbUser '{{ .postgres_user }}'
        POSTGRES_PASSWORD: &dbPass '{{ .postgres_password }}'
        # Postgres init
        INIT_POSTGRES_DBNAME: *dbName
        INIT_POSTGRES_HOST: *dbHost
        INIT_POSTGRES_USER: *dbUser
        INIT_POSTGRES_PASS: *dbPass
        INIT_POSTGRES_SUPER_USER: "{{ .POSTGRES_SUPER_USER }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
  - extract:
      key: kyoo
  - extract:
      key: cloudnative-pg
