---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name kyoo
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: kyoo-secret
    template:
      type: Opaque
      data:
        # App
        KYOO_API_KEY: '{{ .KYOO_API_KEY }}'
        TMDB_API_KEY: '{{ .TMDB_API_KEY }}'
        TVDB_APIKEY: ""
        TVDB_PIN: ""
        # Postgres
        POSTGRES_USER: '{{ .postgres_user }}'
        POSTGRES_PASSWORD: '{{ .postgres_password }}'
  dataFrom:
  - extract:
      key: kyoo
  - extract:
      key: cloudnative-pg
