---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: omada-controller
spec:
  targetNamespace: selfhosted
  components:
    - ../../../../components/kopiur/backup
    - ../../../../components/zeroscaler
  interval: 30m
  path: ./kubernetes/apps/selfhosted/omada-controller/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: false
  dependsOn:
    - name: rook-ceph-cluster
      namespace: rook-ceph
  postBuild:
    substitute:
      APP: omada-controller
      KOPIUR_CAPACITY: "10Gi"
      KOPIUR_PUID: "508"
      KOPIUR_PGID: "508"
