---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app home-assistant-matter-hub
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 3.6.0
      interval: 15m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    cleanupOnFail: true
    remediation:
      retries: 3
      strategy: uninstall
  uninstall:
    keepHistory: false
  values:
    global:
      nameOverride: *app
      fullnameOverride: *app

    controllers:
      home-assistant-matter-hub:
        annotations:
          reloader.stakater.com/auto: "true"
        pod:
          annotations:
            k8s.v1.cni.cncf.io/networks: |
              [{
                "name":"iot-vlan",
                "namespace": "network",
                "ips": ["${MULTUS_HOME_ASSISTANT_MATTER_HUB}/24"],
                "mac": "a0:36:9f:5a:17:7b"
              }]
          securityContext:
            runAsUser: 568
            runAsGroup: 568
            runAsNonRoot: true
            fsGroup: 568
            fsGroupChangePolicy: OnRootMismatch
            seccompProfile: { type: RuntimeDefault }
            sysctls:
              - name: net.ipv6.conf.net1.forwarding
                value: "0"
              - name: net.ipv6.conf.net1.accept_ra
                value: "1"
              - name: net.ipv6.conf.net1.accept_ra_rt_info_max_plen
                value: "64"

        containers:
          app:
            image:
              repository: ghcr.io/t0bst4r/home-assistant-matter-hub
              tag: 3.0.0-alpha.61
              pullPolicy: IfNotPresent
            envFrom:
              - secretRef:
                  name: home-assistant-matter-hub-secret
            env:
              HAMH_LOG_LEVEL: info
              HAMH_WEB_PORT: &port 8482
              HAMH_STORAGE_LOCATION: /data
              HAMH_MDNS_NETWORK_INTERFACE: net1
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 5
            resources:
              requests:
                cpu: 25m
                memory: 150M
              limits:
                memory: 500M
    service:
      app:
        controller: *app
        ports:
          http:
            enabled: true
            primary: true
            protocol: TCP
            port: *port

    persistence:
      config:
        existingClaim: home-assistant-matter-hub
        advancedMounts:
          home-assistant-matter-hub:
            app:
              - path: "/data"

    ingress:
      app:
        enabled: true
        className: internal
        annotations:
          external-dns.alpha.kubernetes.io/target: internal.judahrand.net
        hosts:
          - host: matterhub.judahrand.net
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
