---
apiVersion: v1
kind: ConfigMap
metadata:
  name: immich-database-gatus-ep
  labels:
    gatus.io/enabled: "true"
data:
  config.yaml: |
    endpoints:
      - name: immich-database
        group: infrastructure
        url: tcp://immich-database-rw.media.svc.cluster.local:5432
        interval: 1m
        ui:
          hide-url: true
          hide-hostname: true
        conditions:
          - "[CONNECTED] == true"
        alerts:
          - type: pushover
