---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app matter-server
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    global:
      nameOverride: *app
      fullnameOverride: *app

    controllers:
      matter-server:
        annotations:
          reloader.stakater.com/auto: "true"
        pod:
          annotations:
            k8s.v1.cni.cncf.io/networks: |
              [{
                "name":"iot-vlan",
                "namespace": "network",
                "ips": ["10.0.60.86/24"],
                "mac": "a0:41:a7:15:c3:00"
              }]
          securityContext:
            runAsUser: 0  # Must be run as root user
            runAsGroup: 100
            runAsNonRoot: false  # Must be run as root user
            fsGroup: 100
            fsGroupChangePolicy: OnRootMismatch
            supplementalGroups:
              - 34
            sysctls:
              - name: net.ipv6.conf.net1.forwarding
                value: "0"
              - name: net.ipv6.conf.net1.accept_ra
                value: "1"
              - name: net.ipv6.conf.net1.accept_ra_rt_info_max_plen
                value: "64"

        containers:
          app:
            image:
              repository: ghcr.io/home-assistant-libs/python-matter-server
              tag: 8.1.0
              pullPolicy: IfNotPresent
            args:
              - --storage-path=/data
              - --paa-root-cert-dir=/data/credentials
              - --primary-interface=net1
            env:
              TZ: Europe/London
              MATTER_SERVER__INSTANCE_NAME: Matter-Server
              MATTER_SERVER__PORT: &port 5580
              MATTER_SERVER__APPLICATION_URL: &host matter.judahrand.net
              MATTER_SERVER__LOG_LEVEL: debug
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 5
            resources:
              requests:
                cpu: 15m
                memory: "150M"
              limits:
                memory: "256M"

    service:
      app:
        controller: *app
        type: LoadBalancer
        annotations:
          external-dns.alpha.kubernetes.io/hostname: *host
          io.cilium/lb-ipam-ips: 10.0.42.128
        ports:
          api:
            enabled: true
            primary: true
            protocol: TCP
            port: *port
        externalTrafficPolicy: Cluster

    persistence:
      config:
        existingClaim: matter-server
        advancedMounts:
          matter-server:
            app:
              - path: "/data"

    route:
      app:
        hostnames:
          - "{{ .Release.Name }}.judahrand.net"
        parentRefs:
          - name: internal
            namespace: kube-system
            sectionName: https
        rules:
          - backendRefs:
              - identifier: app
                port: *port
