---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app matter-server
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 3.5.1
      interval: 15m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    cleanupOnFail: true
    remediation:
      retries: 3
      strategy: uninstall
  uninstall:
    keepHistory: false
  values:
    global:
      nameOverride: *app
      fullnameOverride: *app

    controllers:
      matter-server:
        annotations:
          reloader.stakater.com/auto: "true"
        pod:
          annotations:
            k8s.v1.cni.cncf.io/networks: |
              [{
                "name":"multus-servers",
                "namespace": "home",
                "ips": ["10.0.42.86/24"]
              }]
          securityContext:
            runAsUser: 0       # ${APP_UID}   # Must be run as root user
            runAsGroup: ${APP_GID}
            runAsNonRoot: false               # Must be run as root user
            fsGroup: ${APP_GID}
            fsGroupChangePolicy: "OnRootMismatch"
            supplementalGroups:
              - 34

        containers:
          app:
            image:
              repository: ghcr.io/home-assistant-libs/python-matter-server
              tag: 6.5.1
              pullPolicy: IfNotPresent
            env:
              TZ: "${TIMEZONE}"
              MATTER_SERVER__INSTANCE_NAME: Matter-Server
              MATTER_SERVER__PORT: &port 5580
              MATTER_SERVER__APPLICATION_URL: &host "matter.judahrand.net"
              MATTER_SERVER__LOG_LEVEL: info
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 5
            resources:
              requests:
                memory: "100M"
              limits:
                memory: "500M"

    service:
      app:
        controller: *app
        type: LoadBalancer
        annotations:
          io.cilium/lb-ipam-ips: "${LOAD_BALANCER_MATTER_SERVER}"
        ports:
          http:
            enabled: false
            primary: false
            port: 65535
          api:
            enabled: true
            primary: true
            protocol: TCP
            port: *port
        externalTrafficPolicy: Cluster

    persistence:
      config:
        enabled: true
        type: nfs
        path: /mnt/main/matter-server
        server: truenas.lan
        advancedMounts:
          matter-server:
            app:
              - path: "/data"

    ingress:
      app:
        enabled: false
        className: "internal"
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-production
        hosts:
          - host: *host
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
            - *host