---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: home-assistant-matter-hub
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: home-assistant-matter-hub-secret
    template:
      engineVersion: v2
      data:
        HAMH_HOME_ASSISTANT_URL: http://home-assistant.home.svc.cluster.local:8123
        HAMH_HOME_ASSISTANT_ACCESS_TOKEN: "{{ .access_token }}"
  dataFrom:
    - extract:
        key: home-assistant-matter-hub
