---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: omegabrr
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: omegabrr-secret
    template:
      engineVersion: v2
      data:
        config.yaml: |
          server:
            host: 0.0.0.0
            port: 80
            apiToken: {{ .omegabrr_api_key }}

          schedule: "0 */6 * * *" # Every 6 hours

          clients:
            autobrr:
              host: http://autobrr.downloads.svc.cluster.local:7474
              apikey: {{ .autobrr_omegabrr_api_key }}

            arr:
              - name: radarr
                type: radarr
                host: http://radarr.downloads.svc.cluster.local:7878
                apikey: {{ .radarr_api_key }}
                filters: [41]
              - name: sonarr
                type: sonarr
                host: http://sonarr.downloads.svc.cluster.local:8989
                apikey: {{ .sonarr_api_key }}
                filters: [39]
                excludeAlternateTitles: true

          lists:
            - name: Trakt - Judah
              type: trakt
              url: https://api.trakt.tv/users/judahrand/watchlist
              headers:
                trakt-api-key: {{ .omegabrr_trakt_api_key }}
              filters:
                - 72
  dataFrom:
    - extract:
        key: omegabrr
      rewrite:
        - regexp:
            source: "(.*)"
            target: "omegabrr_$1"
    - extract:
        key: autobrr
      rewrite:
        - regexp:
            source: "(.*)"
            target: "autobrr_$1"
    - extract:
        key: radarr
      rewrite:
        - regexp:
            source: "(.*)"
            target: "radarr_$1"
    - extract:
        key: sonarr
      rewrite:
        - regexp:
            source: "(.*)"
            target: "sonarr_$1"

