---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: kopiur-replication
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: kopiur-replication-secret
  data:
    - secretKey: AWS_ACCESS_KEY_ID
      remoteRef:
        key: kopiur
        property: R2_AWS_ACCESS_KEY_ID
    - secretKey: AWS_SECRET_ACCESS_KEY
      remoteRef:
        key: kopiur
        property: R2_AWS_SECRET_ACCESS_KEY
