---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: postfinance
  namespace: &namespace kube-system
spec:
  interval: 1h
  url: https://postfinance.github.io/kubelet-csr-approver
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kubelet-csr-approver
  namespace: &namespace kube-system
spec:
  interval: 30m
  chart:
    spec:
      chart: kubelet-csr-approver
      version: 1.2.7
      sourceRef:
        kind: HelmRepository
        name: postfinance
        namespace: *namespace
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  valuesFrom:
    - kind: ConfigMap
      name: kubelet-csr-approver-values
  values:
    metrics:
      enable: true
      serviceMonitor:
        enabled: true
    resources:
      requests:
        cpu: 1m
        memory: 64Mi
      limits:
        cpu: 50m
