---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kubelet-csr-approver
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: kubelet-csr-approver
  valuesFrom:
    - kind: ConfigMap
      name: kubelet-csr-approver-values
  values:
    metrics:
      enable: true
      serviceMonitor:
        enabled: true
    resources:
      requests:
        cpu: 1m
        memory: 64Mi
      limits:
        cpu: 50m
