---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: sonarr
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: sonarr-secret
    creationPolicy: Owner
  data:
    - secretKey: api_key
      remoteRef:
        key: sonarr
        property: api_key
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: sonarr-db
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: sonarr-db-secret
    template:
      type: Opaque
      data:
        SONARR__POSTGRES__HOST: &dbHost postgres16-rw.database.svc.cluster.local
        SONARR__POSTGRES__PORT: "5432"
        SONARR__POSTGRES__MAINDB: sonarr-main
        SONARR__POSTGRES__LOGDB: sonarr-log
        SONARR__POSTGRES__USER: &dbUser "{{ .username }}"
        SONARR__POSTGRES__PASSWORD: &dbPass "{{ .password }}"
        INIT_POSTGRES_DBNAME: sonarr-main sonarr-log
        INIT_POSTGRES_HOST: *dbHost
        INIT_POSTGRES_USER: *dbUser
        INIT_POSTGRES_PASS: *dbPass
        INIT_POSTGRES_SUPER_USER: "{{ .POSTGRES_SUPER_USER }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
    - extract:
        key: postgres-pguser-sonarr
    - extract:
        key: cloudnative-pg
