---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/postgresql.cnpg.io/cluster_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: immich-database
spec:
  instances: 3
  # renovate: datasource=docker depName=ghcr.io/cloudnative-pg/postgresql
  imageName: ghcr.io/cloudnative-pg/postgresql:18.3-system-bookworm@sha256:9a2cc9f0bf9a67827e214484f83362f1829b3ac839da6d2c2cff902a720d5e5f
  primaryUpdateStrategy: unsupervised
  enablePDB: true

  storage:
    size: 10Gi  # this is not enforced because we're using a hostpath storage class
    storageClass: openebs-hostpath

  superuserSecret:
    name: cloudnative-pg-secret

  enableSuperuserAccess: true

  postgresql:
    extensions:
      - name: vchord
        image:
          # renovate: datasource=docker depName=ghcr.io/tensorchord/vchord-scratch
          reference: ghcr.io/tensorchord/vchord-scratch:pg18-v1.1.1@sha256:bdea43bed2a414e21bbf71767bf6f0739747ac480b267b51772dc214ac28dcb3
        dynamic_library_path:
          - /usr/lib/postgresql/18/lib/
        extension_control_path:
          - /usr/share/postgresql/18/
    shared_preload_libraries:
      - "vchord.so"
    parameters:
      max_connections: "100"
      shared_buffers: 256MB

  managed:
    roles:
      - name: immich
        ensure: present
        login: true
        superuser: false
        inRoles: []
        passwordSecret:
          name: immich-database-secret

  resources:
    requests:
      cpu: 20m
      memory: 512Mi
    limits:
      memory: 4Gi

  monitoring:
    enablePodMonitor: true

  plugins:
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: immich-database
        # Note: serverName version needs to be incremented
        # when recovering from an existing cnpg cluster
        serverName: &currentCluster immich-database-v4

  # bootstrap:
  #   initdb:
  #     database: immich
  #     owner: immich
  #     secret:
  #       name: immich-database-secret
  #     dataChecksums: true
  #     postInitApplicationSQL:
  #       # Commands based on: https://immich.app/docs/administration/postgres-standalone/#without-superuser-permission
  #       - ALTER DATABASE immich OWNER TO immich;
  #       - CREATE EXTENSION vchord CASCADE;
  #       - CREATE EXTENSION earthdistance CASCADE;
  # # Note: previousCluster needs to be set to the name of the previous
  # # cluster when recovering from an existing cnpg cluster
  #   recovery:
  #     source: &previousCluster immich-database-v3
  #
  # # Note: externalClusters is needed when recovering from an existing cnpg cluster
  # externalClusters:
  #   - name: *previousCluster
  #     plugin:
  #       name: barman-cloud.cloudnative-pg.io
  #       parameters:
  #         barmanObjectName: immich-database
  #         serverName: *previousCluster
