---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudnative-pg
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: cloudnative-pg-secret
    template:
      metadata:
        labels:
          cnpg.io/reload: "true"
      data:
        POSTGRES_SUPER_USER: "{{ .username }}"
        POSTGRES_SUPER_PASS: "{{ .password }}"
        MINIO_USER: "{{ .aws-access-key-id }}"
        MINIO_PASSWORD: "{{ .aws-secret-access-key }}"
  dataFrom:
    - extract:
        key: cloudnative-pg
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: immich-database
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: immich-database-secret
    template:
      metadata:
        labels:
          cnpg.io/reload: "true"
      data:
        username: "{{ .postgres_user }}"
        password: "{{ .postgres_password }}"
  dataFrom:
    - extract:
        key: immich-server
