---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: radarr
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: radarr-secret
    creationPolicy: Owner
  data:
    - secretKey: api_key
      remoteRef:
        key: radarr
        property: api_key
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: radarr-db
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: radarr-db-secret
    template:
      type: Opaque
      data:
        RADARR__POSTGRES__HOST: postgres16-rw.database.svc.cluster.local
        RADARR__POSTGRES__PORT: "5432"
        RADARR__POSTGRES__MAINDB: radarr-main
        RADARR__POSTGRES__LOGDB: radarr-log
        RADARR__POSTGRES__USER: '{{ .username }}'
        RADARR__POSTGRES__PASSWORD: '{{ .password }}'
  dataFrom:
    - extract:
        key: postgres-pguser-radarr
