---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: radarr
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: radarr-secret
    template:
      data:
        RADARR__AUTH__APIKEY: "{{ .api_key }}"
        RADARR__POSTGRES__HOST: &dbHost postgres16-rw.database.svc.cluster.local
        RADARR__POSTGRES__PORT: "5432"
        RADARR__POSTGRES__MAINDB: radarr-main
        RADARR__POSTGRES__LOGDB: radarr-log
        RADARR__POSTGRES__USER: &dbUser "{{ .username }}"
        RADARR__POSTGRES__PASSWORD: &dbPass "{{ .password }}"
        INIT_POSTGRES_DBNAME: radarr-main radarr-log
        INIT_POSTGRES_HOST: *dbHost
        INIT_POSTGRES_USER: *dbUser
        INIT_POSTGRES_PASS: *dbPass
        INIT_POSTGRES_SUPER_USER: "{{ .POSTGRES_SUPER_USER }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
    - extract:
        key: radarr
    - extract:
        key: postgres-pguser-radarr
    - extract:
        key: cloudnative-pg
