---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: observability
components:
  - ../../components/common
resources:
  - ./blackbox-exporter/ks.yaml
  - ./gatus/ks.yaml
  - ./grafana/ks.yaml
  - ./graphite-exporter/ks.yaml
  - ./kube-prometheus-stack/ks.yaml
  - ./kromgo/ks.yaml
  - ./loki/ks.yaml
  - ./network-ups-tools/ks.yaml
  - ./nut-exporter/ks.yaml
  - ./promtail/ks.yaml
  - ./silence-operator/ks.yaml
  - ./smartctl-exporter/ks.yaml
patches:
  - patch: |-
      apiVersion: v1
      kind: Namespace
      metadata:
        name: not-used
        labels:
          pod-security.kubernetes.io/enforce: privileged
