---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  # Load balancer IPs
  LOAD_BALANCER_INTERNAL_NGINX: 10.0.42.121
  LOAD_BALANCER_POSTGRES: 10.0.42.125
  LOAD_BALANCER_EMQX: 10.0.42.126
  LOAD_BALANCER_FRIGATE: 10.0.42.127
