---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app network-ups-tools
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      network-ups-tools:
        strategy: RollingUpdate
        containers:
          app:
            image:
              repository: ghcr.io/judahrand/network-ups-tools
              tag: v2.8.2@sha256:d53749e75fdc0cc8b9a109d39b4bec368caff93321536361b74b8f9374ddcc23
            env:
              TZ: Europe/London
            securityContext:
              privileged: true
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
        pod:
          annotations:
            configmap.reloader.stakater.com/reload: &config network-ups-tools-config
    defaultPodOptions:
      securityContext:
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
    service:
      app:
        controller: *app
        type: LoadBalancer
        annotations:
          external-dns.alpha.kubernetes.io/hostname: nut.judahrand.net
          io.cilium/lb-ipam-ips: 10.0.42.30, ::ffff:10.0.42.30
        externalTrafficPolicy: Cluster
        ports:
          http:
            port: 3493
            protocol: TCP
    persistence:
      config:
        type: configMap
        name: *config
        defaultMode: 0400
        globalMounts:
          - path: /etc/nut
