---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app esphome
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      esphome:
        annotations:
          reloader.stakater.com/auto: "true"
        pod:
          annotations:
            k8s.v1.cni.cncf.io/networks: |
              [{
                "name":"iot-vlan",
                "namespace": "network",
                "ips": ["10.0.60.85/24"],
                "mac": "a0:41:a7:c5:0c:d9"
              }]
          securityContext:
            runAsUser: 568
            runAsGroup: 568
            fsGroup: 568
            fsGroupChangePolicy: OnRootMismatch

        containers:
          app:
            image:
              repository: ghcr.io/home-operations/esphome
              tag: 2025.2.2
              pullPolicy: IfNotPresent
            env:
              TZ: Europe/London
              ESPHOME__INSTANCE_NAME: ESPHome
              ESPHOME__PORT: &port 6052
              ESPHOME__APPLICATION_URL: &host "esphome.judahrand.net"
              ESPHOME__LOG_LEVEL: info
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 5
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 15m
                memory: "100M"
              limits:
                memory: "8G"

    service:
      app:
        controller: *app
        ports:
          http:
            port: *port

    persistence:
      config:
        existingClaim: esphome
        advancedMounts:
          esphome:
            app:
              - path: /config
      cache:
        type: emptyDir
        advancedMounts:
          esphome:
            app:
              - path: /cache

    route:
      app:
        hostnames:
          - "{{ .Release.Name }}.judahrand.net"
        parentRefs:
          - name: internal
            namespace: kube-system
            sectionName: https
        rules:
          - backendRefs:
              - name: app
                port: *port
