---
originRequest:
  originServerName: external.judahrand.net

ingress:
  - hostname: judahrand.net
    service: &svc https://cilium-gateway-external.kube-system.svc.cluster.local
  - hostname: "*.judahrand.net"
    service: *svc
  - service: http_status:404
