---
originRequest:
  originServerName: external.judahrand.net

ingress:
  - hostname: judahrand.net
    service: https://nginx-external-controller.network.svc.cluster.local:443
  - hostname: "*.judahrand.net"
    service: https://nginx-external-controller.network.svc.cluster.local:443
  - service: http_status:404
