---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app otbr
spec:

  interval: 15m

  chart:
    spec:
      chart: app-template
      version: 3.5.1
      interval: 15m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  maxHistory: 3

  install:
    createNamespace: true
    remediation:
      retries: 3

  upgrade:
    crds: CreateReplace
    cleanupOnFail: true
    remediation:
      retries: 3
      strategy: uninstall

  uninstall:
    keepHistory: false

  values:

    controllers:

      *app :

        annotations:
          reloader.stakater.com/auto: "true"

        pod:
          annotations:
            k8s.v1.cni.cncf.io/networks: |
              [{
                "name":"iot-vlan",
                "namespace": "network",
                "ips": ["${MULTUS_OTBR}/24"],
                "mac": "a0:41:a7:5b:03:de"
              }]
          securityContext:
            runAsNonRoot: false
            runAsUser: 0
            runAsGroup: 0
            fsGroup: 0
            fsGroupChangePolicy: OnRootMismatch

        initContainers:
          socat:
            image:
              repository: alpine/socat
              tag: 1.8.0.0
            args:
              - -d
              - pty,raw,echo=0,link=/tmp/ttyOTBR,ignoreeof
              - tcp:10.0.60.245:6638
            restartPolicy: Always

        containers:
          *app :
            image:
              repository: openthread/otbr
              tag: jammy
              pullPolicy: IfNotPresent

            env:
              TZ: "${TIMEZONE}"
              RADIO_URL: spinel+hdlc+uart:///tmp/ttyOTBR?uart-baudrate=460800&uart-flow-control
              INFRA_IF_NAME: net1
            securityContext:
              privileged: true
              allowPrivilegeEscalation: true
              readOnlyRootFilesystem: false
              sysctls:
                - name: net.ipv6.conf.all.disable_ipv6
                  value: "0"
                - name: net.ipv4.conf.all.forwarding
                  value: "1"
                - name: net.ipv6.conf.all.forwarding
                  value: "1"

            resources:
              requests:
                memory: "100M"
              limits:
                memory: "500M"

    service:
      *app :
        controller: *app
        ports:
          http:
            port: 80
            primary: true
          rest:
            port: 8081

    ingress:
      *app :
        annotations:
          external-dns.alpha.kubernetes.io/target: internal.judahrand.net
        className: internal
        hosts:
          - host: otbr.judahrand.net
            paths:
              - path: /
                service:
                  identifier: *app
                  port: http

    persistence:
      tmp:
        type: emptyDir
        globalMounts:
          - path: /tmp
