---
apiVersion: v1
kind: ConfigMap
metadata:
  name: immich-server-config
data:
  # URLS
  IMMICH_SERVER_URL: http://immich-server:3001
  PUBLIC_IMMICH_SERVER_URL: https://immich.judahrand.net

  # REDIS
  REDIS_HOSTNAME: "immich-redis"
  REDIS_PORT: "6379"
