---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app immich-server
spec:
  interval: 1h
  chart:
    spec:
      chart: app-template
      version: 3.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 1h
  maxHistory: 3
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:

      immich-server:
        strategy: RollingUpdate
        annotations:
          reloader.stakater.com/auto: "true"

        initContainers:
          init-db:
            image:
              repository: ghcr.io/onedr0p/postgres-init
              tag: 16
            envFrom:
              - secretRef:
                  name: immich-server-secret

        containers:
          main:
            image:
              repository: ghcr.io/immich-app/immich-server
              tag: v1.122.1

            resources:
              requests:
                cpu: 100m
                memory: 256Mi
              limits:
                memory: 4096Mi

            env:
              LOG_LEVEL: verbose
              IMMICH_MEDIA_LOCATION: &mediaLocation /usr/src/app/upload
              SERVER_PORT: &port 2283

            envFrom:
              - secretRef:
                  name: immich-server-secret
              - configMapRef:
                  name: immich-server-config

            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /api/server/ping
                    port: *port
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
              startup:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /api/server/ping
                    port: *port
                  failureThreshold: 30
                  periodSeconds: 5
                  successThreshold: 1
                  timeoutSeconds: 1

    service:
      main:
        controller: immich-server
        ports:
          http:
            port: *port

    ingress:
      main:
        enabled: true
        className: external
        annotations:
          external-dns.alpha.kubernetes.io/target: external.judahrand.net
          nginx.ingress.kubernetes.io/proxy-body-size: "0"
        hosts:
          - host: &host immich.judahrand.net
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: main
                  port: http

    persistence:
      data:
        type: nfs
        server: truenas.lan
        path: /mnt/main/immich
        globalMounts:
          - path: *mediaLocation
