---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zigbee2mqtt
spec:
  selector:
    matchLabels:
      app: &app zigbee2mqtt
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: zigbee2mqtt
    spec:
      securityContext:
        fsGroup: 568
      containers:
        - name: main
          image: ghcr.io/koenkk/zigbee2mqtt:2.3.0@sha256:42de8c55dc578a8404a18c43aeb2b7c75be7988179abe9a8195d99a9e7ebb917
          envFrom:
            - configMapRef:
                name: zigbee2mqtt-config
            - secretRef:
                name: zigbee2mqtt-secret
          env:
            - name: "ZIGBEE2MQTT_CONFIG_FRONTEND_ENABLED"
              value: "true"
            - name: "ZIGBEE2MQTT_CONFIG_FRONTEND_PORT"
              value: "8080"
            - name: "ZIGBEE2MQTT_CONFIG_FRONTEND_URL"
              value: https://zigbee2mqtt.judahrand.net
          ports:
            - containerPort: &port 8080
              name: http
          readinessProbe:
            httpGet:
              path: /
              port: *port
            failureThreshold: 5
            initialDelaySeconds: 5
            timeoutSeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: *port
            failureThreshold: 5
            initialDelaySeconds: 10
            timeoutSeconds: 10
            periodSeconds: 30
          resources:
            requests:
              cpu: 100m
              memory: 250M
            limits:
              memory: 250M
          volumeMounts:
            - name: data
              mountPath: /data
            - name: healthcheck
              mountPath: /healthcheck.sh
              subPath: healthcheck.sh
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: *app
        - name: healthcheck
          configMap:
            name: zigbee2mqtt-healthcheck
            items:
              - key: healthcheck.sh
                path: healthcheck.sh
