---
# yaml-language-server: $schema=https://schemas.recyclarr.dev/v8/config-schema.json
sonarr:
  series:
    base_url: http://sonarr.downloads.svc.cluster.local
    api_key: !env_var SONARR_API_KEY

    quality_definition:
      type: series

    quality_profiles:
      - trash_id: 72dae194fc92bf828f32cde7744e51a1 # WEB-1080p
        reset_unmatched_scores:
          enabled: true
      - trash_id: d1498e7d189fbe6c7110ceaabb7473e6 # WEB-2160p
        reset_unmatched_scores:
          enabled: true

    custom_format_groups:
      add:
        - trash_id: 158188097a58d7687dee647e04af0da3 # [Optional] Golden Rule HD
          assign_scores_to:
            - trash_id: 72dae194fc92bf828f32cde7744e51a1 # WEB-1080p
          # Allow x265 HD and x265 (no HDR/DV) releases.
          exclude:
            - 47435ece6b99a0b477caf360e79ba0bb # x265 (HD)
          select:
            - 9b64dff695c2115facf1b6ea59c9bd07 # x265 (no HDR/DV)
        - trash_id: e3f37512790f00d0e89e54fe5e790d1c # [Optional] Golden Rule UHD
          assign_scores_to:
            - trash_id: d1498e7d189fbe6c7110ceaabb7473e6 # WEB-2160p
          # Allow x265 HD and x265 (no HDR/DV) releases.
          exclude:
            - 9b64dff695c2115facf1b6ea59c9bd07 # x265 (no HDR/DV)
          select:
            - 47435ece6b99a0b477caf360e79ba0bb # x265 (HD)
        - trash_id: 59c3af66780d08332fdc64e68297098f # [Unwanted] Unwanted Formats
          assign_scores_to:
            - trash_id: 72dae194fc92bf828f32cde7744e51a1 # WEB-1080p
            - trash_id: d1498e7d189fbe6c7110ceaabb7473e6 # WEB-2160p
          select:
            - 82d40da2bc6923f41e14394075dd4b03 # No-RlsGroup
            - e1a997ddb54e3ecbfe06341ad323c458 # Obfuscated
            - 06d66ab109d4d2eddb2794d21526d140 # Retags
            - 1b3994c551cbb92a2c781af061f4ab44 # Scene
        - trash_id: e1053c0ef622df3749fa43c22865663a # [HDR Formats] SDR
          assign_scores_to:
            - trash_id: d1498e7d189fbe6c7110ceaabb7473e6 # WEB-2160p
          # Block SDR releases on the UHD profile.
          select:
            - 2016d1676f5ee13a5b7257ff86ac9a93 # SDR

radarr:
  movies:
    base_url: http://radarr.downloads.svc.cluster.local
    api_key: !env_var RADARR_API_KEY

    quality_definition:
      type: sqp-uhd

    quality_profiles:
      - trash_id: 5128baeb2b081b72126bc8482b2a86a0 # [SQP] SQP-1 (2160p)
        reset_unmatched_scores:
          enabled: true
      - trash_id: c3933358ba2356bafc41524f81471069 # [SQP] SQP-2
        reset_unmatched_scores:
          enabled: true

    custom_format_groups:
      add:
        - trash_id: 15b1cf0b6f1a1493856a4355907affee # [Unwanted] Unwanted Formats SQP
          assign_scores_to:
            - trash_id: 5128baeb2b081b72126bc8482b2a86a0 # SQP-1 (2160p)
            - trash_id: c3933358ba2356bafc41524f81471069 # SQP-2
          select:
            - ae9b7c9ebde1f3bd336a8cbd1ec4c5e5 # No-RlsGroup
            - 7357cf5161efbf8c4d5d0c30b4815ee2 # Obfuscated
            - 5c44f52a8714fdd79bb4d98e2673be1f # Retags
            - f537cf427b64c38c8e36298f657e4828 # Scene
        - trash_id: f4f1474b963b24cf983455743aa9906c # [Optional] Movie Versions
          assign_scores_to:
            - trash_id: 5128baeb2b081b72126bc8482b2a86a0 # SQP-1 (2160p)
          # Prefer these movie versions.
          select:
            - eca37840c13c6ef2dd0262b141a5482f # 4K Remaster
            - e0c07d59beb37348e975a930d5e50319 # Criterion Collection
            - 9f6cbff8cfe4ebbc1bde14c7b7bec0de # IMAX Enhanced
            - 9d27d9d2181838f76dee150882bdc58c # Masters of Cinema
            - 570bc9ebecd92723d2d21500f4be314c # Remaster
            - 957d0f44b592285f26449575e8b1167e # Special Edition
            - db9b4c4b53d312a3ca5f1378f6440fc9 # Vinegar Syndrome
        - trash_id: f4f1474b963b24cf983455743aa9906c # [Optional] Movie Versions
          assign_scores_to:
            - trash_id: c3933358ba2356bafc41524f81471069 # SQP-2
          # Prefer these movie versions.
          select:
            - 0f12c086e289cf966fa5948eac571f44 # Hybrid
            - 570bc9ebecd92723d2d21500f4be314c # Remaster
            - eca37840c13c6ef2dd0262b141a5482f # 4K Remaster
            - e0c07d59beb37348e975a930d5e50319 # Criterion Collection
            - 9d27d9d2181838f76dee150882bdc58c # Masters of Cinema
            - db9b4c4b53d312a3ca5f1378f6440fc9 # Vinegar Syndrome
            - 957d0f44b592285f26449575e8b1167e # Special Edition
            - eecf3a857724171f968a66cb5719e152 # IMAX
            - 9f6cbff8cfe4ebbc1bde14c7b7bec0de # IMAX Enhanced
        - trash_id: c4492eebd0c2ddc14c2c91623aa7f95d # [Optional] Miscellaneous SQP
          assign_scores_to:
            - trash_id: c3933358ba2356bafc41524f81471069 # SQP-2
          select:
            - f700d29429c023a5734505e77daeaea7 # DV (Disk)
        - trash_id: 47f0d69750de9e16855915fa73bb7b08 # [HDR Formats] SDR
          assign_scores_to:
            - trash_id: 5128baeb2b081b72126bc8482b2a86a0 # SQP-1 (2160p)
            - trash_id: c3933358ba2356bafc41524f81471069 # SQP-2
          # Block SDR releases.
          select:
            - 9c38ebb7384dada637be8899efa68e6f # SDR
