---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: system-upgrade
components:
  - ../../components/common
resources:
  - ./system-upgrade-controller/ks.yaml
configMapGenerator:
  - name: versions
    env: ./versions.env
configurations:
  - ./kustomizeconfig.yaml
patches:
  - patch: |-
      apiVersion: v1
      kind: Namespace
      metadata:
        name: not-used
        labels:
          pod-security.kubernetes.io/enforce: privileged
