---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app home-assistant
  namespace: flux-system
spec:
  targetNamespace: home
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  components:
    - ../../../../components/gatus/external
    - ../../../../components/volsync
  interval: 30m
  timeout: 5m
  path: ./kubernetes/apps/home/home-assistant/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: false
  dependsOn:
    - name: multus-config
      namespace: network
    - name: cloudnative-pg-cluster
      namespace: cnpg-system
    - name: external-secrets
      namespace: external-secrets
  postBuild:
    substitute:
      APP: *app
      GATUS_SUBDOMAIN: homeassistant
      VOLSYNC_CAPACITY: 5Gi
