---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app immich-machine-learning
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  dependsOn:
    - name: immich-server
      namespace: media

  values:
    controllers:
      immich-machine-learning:
        containers:
          app:
            image:
              repository: ghcr.io/immich-app/immich-machine-learning
              tag: v1.131.2
            env:
              # General
              IMMICH_MEDIA_LOCATION: &mediaLocation /usr/src/app/upload
              # Ports
              MACHINE_LEARNING_HOST: 0.0.0.0
              MACHINE_LEARNING_PORT: &port 3003
              # Machine learning
              MACHINE_LEARNING_CACHE_FOLDER: /cache
              TRANSFORMERS_CACHE: /cache
            resources:
              requests:
                cpu: 100m
                memory: 256Mi
              limits:
                memory: 4096Mi

    service:
      app:
        controller: immich-machine-learning
        ports:
          http:
            port: *port

    persistence:
      library:
        type: nfs
        server: truenas.servers
        path: /mnt/main/immich
        globalMounts:
          - path: *mediaLocation

      cache:
        existingClaim: immich-machine-learning-cache
        globalMounts:
          - path: /cache
