---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: rook-ceph
spec:
  targetNamespace: rook-ceph
  path: ./kubernetes/apps/rook-ceph/rook-ceph/app
  prune: false # never should be deleted
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: false
  interval: 30m
---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: rook-ceph-cluster
spec:
  targetNamespace: rook-ceph
  dependsOn:
    - name: ceph-csi-drivers
      namespace: rook-ceph
    - name: rook-ceph
      namespace: rook-ceph
  path: ./kubernetes/apps/rook-ceph/rook-ceph/cluster
  prune: false # never should be deleted
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: false
  interval: 30m
  postBuild:
    substitute:
      APP: rook-ceph-cluster
  healthCheckExprs:
    - apiVersion: ceph.rook.io/v1
      kind: CephCluster
      failed: status.ceph.health == 'HEALTH_ERR'
      current: status.ceph.health in ['HEALTH_OK', 'HEALTH_WARN']
