---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/source.toolkit.fluxcd.io/ocirepository_v1beta2.json
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: rook-ceph
spec:
  interval: 5m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: v1.17.2
  url: oci://ghcr.io/rook/rook-ceph
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rook-ceph-operator
spec:
  interval: 1h
  timeout: 15m
  chartRef:
    kind: OCIRepository
    name: rook-ceph
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    csi:
      cephFSKernelMountOptions: ms_mode=prefer-crc
      enableLiveness: true
      serviceMonitor:
        enabled: true

      # -- CEPH CSI RBD provisioner resource requirement list
      # csi-omap-generator resources will be applied only if `enableOMAPGenerator` is set to `true`
      # @default -- see values.yaml
      csiRBDProvisionerResource: |
        - name : csi-provisioner
          resource:
            requests:
              memory: 128Mi
              cpu: 100m
            limits:
              memory: 256Mi
        - name : csi-resizer
          resource:
            requests:
              memory: 15Mi
              cpu: 1m
            limits:
              memory: 256Mi
        - name : csi-attacher
          resource:
            requests:
              memory: 10Mi
              cpu: 1m
            limits:
              memory: 256Mi
        - name : csi-snapshotter
          resource:
            requests:
              memory: 10Mi
              cpu: 1m
            limits:
              memory: 256Mi
        - name : csi-rbdplugin
          resource:
            requests:
              cpu: 5m
              memory: 128Mi
            limits:
              memory: 1Gi
        - name : csi-omap-generator
          resource:
            requests:
              memory: 512Mi
              cpu: 250m
            limits:
              memory: 1Gi
        - name : liveness-prometheus
          resource:
            requests:
              memory: 30Mi
              cpu: 1m
            limits:
              memory: 256Mi

      # -- CEPH CSI RBD plugin resource requirement list
      # @default -- see values.yaml
      csiRBDPluginResource: |
        - name : driver-registrar
          resource:
            requests:
              memory: 10Mi
              cpu: 1m
            limits:
              memory: 256Mi
        - name : csi-rbdplugin
          resource:
            requests:
              memory: 64Mi
              cpu: 1m
            limits:
              memory: 1Gi
        - name : liveness-prometheus
          resource:
            requests:
              memory: 30Mi
              cpu: 1m
            limits:
              memory: 256Mi

      # -- CEPH CSI CephFS provisioner resource requirement list
      # @default -- see values.yaml
      csiCephFSProvisionerResource: |
        - name : csi-provisioner
          resource:
            requests:
              memory: 64Mi
              cpu: 1m
            limits:
              memory: 256Mi
        - name : csi-resizer
          resource:
            requests:
              memory: 64Mi
              cpu: 1m
            limits:
              memory: 256Mi
        - name : csi-attacher
          resource:
            requests:
              memory: 64Mi
              cpu: 1m
            limits:
              memory: 256Mi
        - name : csi-snapshotter
          resource:
            requests:
              memory: 64Mi
              cpu: 1m
            limits:
              memory: 256Mi
        - name : csi-cephfsplugin
          resource:
            requests:
              memory: 64Mi
              cpu: 1m
            limits:
              memory: 1Gi
        - name : liveness-prometheus
          resource:
            requests:
              memory: 30Mi
              cpu: 1m
            limits:
              memory: 256Mi

      # -- CEPH CSI CephFS plugin resource requirement list
      # @default -- see values.yaml
      csiCephFSPluginResource: |
        - name : driver-registrar
          resource:
            requests:
              memory: 10Mi
              cpu: 1m
            limits:
              memory: 256Mi
        - name : csi-cephfsplugin
          resource:
            requests:
              memory: 64Mi
              cpu: 1m
            limits:
              memory: 1Gi
        - name : liveness-prometheus
          resource:
            requests:
              memory: 30Mi
              cpu: 1m
            limits:
              memory: 256Mi

      # -- CEPH CSI NFS provisioner resource requirement list
      # @default -- see values.yaml
      csiNFSProvisionerResource: |
        - name : csi-provisioner
          resource:
            requests:
              memory: 64Mi
              cpu: 100m
            limits:
              memory: 256Mi
        - name : csi-nfsplugin
          resource:
            requests:
              memory: 64Mi
              cpu: 1m
            limits:
              memory: 1Gi
        - name : csi-attacher
          resource:
            requests:
              memory: 64Mi
              cpu: 1m
            limits:
              memory: 1Gi

      # -- CEPH CSI NFS plugin resource requirement list
      # @default -- see values.yaml
      csiNFSPluginResource: |
        - name : driver-registrar
          resource:
            requests:
              memory: 10Mi
              cpu: 1m
            limits:
              memory: 256Mi
        - name : csi-nfsplugin
          resource:
            requests:
              memory: 64Mi
              cpu: 1m
            limits:
              memory: 1Gi

    monitoring:
      enabled: true

    resources:
      requests:
        memory: 128Mi # unchangable
        cpu: 100m # unchangable
      limits:
        memory: 1Gi
