---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: truenas-backup
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.5.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  values:
    controllers:
      snapshot:
        type: cronjob

        annotations:
          reloader.stakater.com/auto: "true"

        cronjob: &cronJobSpec
          schedule: "@hourly"
          timeZone: "${TIMEZONE}"
          concurrencyPolicy: Forbid
          successfulJobsHistory: 1
          failedJobsHistory: 1

        defaultContainerOptions: &defaultContainerOptions
          env:
            RUSTIC_NO_CACHE: "true"
            RUSTIC_REPOSITORY: opendal:s3
          envFrom:
            - secretRef:
                name: truenas-backup-secret
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities: { drop: ["ALL"] }

        initContainers:
          export:
            image:
              repository: docker.io/library/busybox
              tag: 1.37.0
            args: ["/scripts/export.sh", "/backup"]

        containers:
          backup:
            image: &rusticImage
              repository: ghcr.io/rustic-rs/rustic
              tag: v0.9.4
            args:
              - backup
              - --init
              - /backup
          forget:
            image: *rusticImage
            args:
              - forget
              - --keep-daily=7
              - --keep-weekly=4

      prune:
        type: cronjob

        annotations:
          reloader.stakater.com/auto: "true"

        cronjob:
          <<: *cronJobSpec
          schedule: "@weekly"

        defaultContainerOptions: *defaultContainerOptions

        containers:
          prune:
            image: *rusticImage
            args:
              - prune

    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 568
        runAsGroup: 568
        fsGroup: 568
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile: { type: RuntimeDefault }

    persistence:
      backup:
        type: emptyDir
      scripts:
        type: configMap
        name: truenas-backup
        defaultMode: 0550
