
---
# yaml-language-server: $schema=https://kubernetes-schemas.ok8.sh/helm.toolkit.fluxcd.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: amd-gpu-device-plugin
spec:
  interval: 30m
  chart:
    spec:
      chart: amd-gpu
      version: 0.16.0
      sourceRef:
        kind: HelmRepository
        name: amd-gpu
        namespace: flux-system
  install:
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    crds: CreateReplace
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  dependsOn:
    - name: node-feature-discovery
      namespace: kube-system
  values:
    node_selector_enabled: true
    dp:
      resources:
        requests:
          cpu: 1m
          memory: 64Mi
        limits:
          cpu: 50m
          memory: 128Mi
