---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: truenas-backup
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: truenas-backup-secret
    template:
      engineVersion: v2
      data:
        TRUENAS_HOST: "{{ .host }}"
        TRUENAS_API_KEY: "{{ .api_key }}"
        RUSTIC_PASSWORD: "{{ .restic_password }}"
        OPENDAL_ACCESS_KEY_ID: "{{ .aws_access_key_id }}"
        OPENDAL_SECRET_ACCESS_KEY: "{{ .aws_secret_access_key }}"
        OPENDAL_ENDPOINT: "{{ .s3_endpoint }}"
        OPENDAL_BUCKET: "{{ .s3_bucket }}"
        OPENDAL_REGION: "{{ .s3_region }}"
  dataFrom:
    - extract:
        key: truenas
