---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: truenas-backup
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3

  values:
    controllers:
      snapshot:
        type: cronjob

        annotations:
          reloader.stakater.com/auto: "true"

        cronjob: &cronJobSpec
          schedule: "@daily"
          timeZone: Europe/London
          concurrencyPolicy: Forbid
          successfulJobsHistory: 1
          failedJobsHistory: 1

        defaultContainerOptions: &defaultContainerOptions
          env:
            RUSTIC_NO_CACHE: "true"
            RUSTIC_REPOSITORY: opendal:s3
          envFrom:
            - secretRef:
                name: truenas-backup-secret
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities: { drop: ["ALL"] }

        initContainers:
          export:
            image:
              repository: docker.io/library/busybox
              tag: 1.37.0
            args: ["/scripts/export.sh", "/backup"]

        containers:
          backup:
            image: &rusticImage
              repository: ghcr.io/rustic-rs/rustic
              tag: v0.9.5
            args:
              - backup
              - --init
              - /backup
          forget:
            image: *rusticImage
            args:
              - forget
              - --keep-daily=7
              - --keep-weekly=4

      prune:
        type: cronjob

        annotations:
          reloader.stakater.com/auto: "true"

        cronjob:
          <<: *cronJobSpec
          schedule: "@weekly"

        defaultContainerOptions: *defaultContainerOptions

        containers:
          prune:
            image: *rusticImage
            args:
              - prune

    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 568
        runAsGroup: 568
        fsGroup: 568
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile: { type: RuntimeDefault }

    persistence:
      backup:
        type: emptyDir
      scripts:
        type: configMap
        name: truenas-backup
        defaultMode: 0550
        advancedMounts:
          snapshot:
            export:
              - path: /scripts/export.sh
                subPath: export.sh
