---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: openebs
spec:
  interval: 30m
  chart:
    spec:
      chart: openebs
      version: 4.1.0
      sourceRef:
        kind: HelmRepository
        name: openebs
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    engines:
      local:
        lvm:
          enabled: false
        zfs:
          enabled: false
      replicated:
        mayastor:
          enabled: true
          io_engine:
            resources:
              limits:
                cpu: "250m"
              requests:
                cpu: "250m"
    openebs-crds:
      csi:
        volumeSnapshots:
          enabled: false
    localpv-provisioner:
      localpv:
        basePath: /var/local/openebs
        image:
          registry: quay.io/
      helperPod:
        image:
          registry: quay.io/
