---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app immich-server
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:

      immich-server:
        strategy: RollingUpdate
        annotations:
          reloader.stakater.com/auto: "true"

        initContainers:
          init-db:
            image:
              repository: ghcr.io/home-operations/postgres-init
              tag: 17.4
            envFrom:
              - secretRef:
                  name: immich-server-secret

        containers:
          main:
            image:
              repository: ghcr.io/immich-app/immich-server
              tag: v1.132.1

            resources:
              requests:
                cpu: 100m
                memory: 256Mi
              limits:
                memory: 4096Mi

            env:
              LOG_LEVEL: verbose
              IMMICH_MEDIA_LOCATION: &mediaLocation /usr/src/app/upload
              SERVER_PORT: &port 2283

            envFrom:
              - secretRef:
                  name: immich-server-secret
              - configMapRef:
                  name: immich-server-config

            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /api/server/ping
                    port: *port
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
              startup:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /api/server/ping
                    port: *port
                  failureThreshold: 30
                  periodSeconds: 5
                  successThreshold: 1
                  timeoutSeconds: 1

    service:
      main:
        controller: immich-server
        ports:
          http:
            port: *port

    route:
      app:
        hostnames:
          - &host immich.judahrand.net
        parentRefs:
          - name: external
            namespace: kube-system
            sectionName: https
        rules:
          - backendRefs:
              - name: *app
                port: *port

    persistence:
      data:
        type: nfs
        server: truenas.servers
        path: /mnt/main/immich
        globalMounts:
          - path: *mediaLocation
